# Generated by Django 3.0.4 on 2020-03-31 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('whose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codeapp.Developer')),
            ],
        ),
    ]
