# Generated by Django 3.0.4 on 2020-04-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeapp', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
