# Generated by Django 3.0.4 on 2020-04-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeapp', '0003_developer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='githublink',
        ),
        migrations.AddField(
            model_name='developer',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='github',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='linkedinlink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='developer',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
